#!/usr/bin/env node

/**
 * Setup script for Supabase environment variables
 * 
 * This script helps you set up your .env.local file with the required
 * Supabase configuration values.
 * 
 * Usage: node scripts/setup-env.js
 *    or: npm run setup:env
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const ENV_FILE = path.join(process.cwd(), '.env.local');
const REQUIRED_VARS = {
  NEXT_PUBLIC_SUPABASE_URL: {
    description: 'Supabase Project URL',
    hint: 'Find this in your Supabase project settings under API (e.g., https://xxxxx.supabase.co)',
    validate: (value) => {
      if (!value.trim()) {
        return 'URL cannot be empty';
      }
      if (!/^https?:\/\//i.test(value.trim())) {
        return 'URL must start with http:// or https://';
      }
      return null;
    }
  },
  NEXT_PUBLIC_SUPABASE_ANON_KEY: {
    description: 'Supabase Anonymous Key',
    hint: 'Find this in your Supabase project settings under API (also called "anon" or "public" key)',
    validate: (value) => {
      if (!value.trim()) {
        return 'Key cannot be empty';
      }
      if (value.trim().length < 20) {
        return 'Key appears to be too short. Please verify you copied the full key.';
      }
      return null;
    }
  }
};

// Create readline interface
const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

// Helper function to prompt for input
function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

// Read existing .env.local file
function readExistingEnv() {
  const env = {};
  if (fs.existsSync(ENV_FILE)) {
    const content = fs.readFileSync(ENV_FILE, 'utf8');
    const lines = content.split('\n');
    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed && !trimmed.startsWith('#')) {
        const match = trimmed.match(/^([^=]+)=(.*)$/);
        if (match) {
          const key = match[1].trim();
          const value = match[2].trim().replace(/^["']|["']$/g, '');
          env[key] = value;
        }
      }
    }
  }
  return env;
}

// Write .env.local file
function writeEnvFile(env) {
  let content = '# Supabase Configuration\n';
  content += '# This file is automatically generated by the setup script.\n';
  content += '# Do not commit this file to version control.\n\n';
  
  for (const [key, value] of Object.entries(env)) {
    // Escape special characters and wrap in quotes if needed
    const escapedValue = value.includes(' ') || value.includes('#') 
      ? `"${value.replace(/"/g, '\\"')}"` 
      : value;
    content += `${key}=${escapedValue}\n`;
  }
  
  fs.writeFileSync(ENV_FILE, content, 'utf8');
}

// Validate URL format
function validateUrl(url) {
  return /^https?:\/\/.+/i.test(url.trim());
}

async function showInstructions() {
  console.log('\n' + '='.repeat(70));
  console.log('📖 HOW TO GET YOUR SUPABASE CREDENTIALS');
  console.log('='.repeat(70));
  console.log('\nFollow these steps to find your Supabase credentials:\n');
  
  console.log('1️⃣  Open your web browser and go to:');
  console.log('   👉 https://app.supabase.com\n');
  
  console.log('2️⃣  Sign in to your Supabase account');
  console.log('   (Don\'t have an account? Create one for free at supabase.com)\n');
  
  console.log('3️⃣  Select your project from the dashboard');
  console.log('   (Or create a new project if you don\'t have one yet)\n');
  
  console.log('4️⃣  In the left sidebar, click on "Settings" (⚙️ icon)\n');
  
  console.log('5️⃣  Click on "API" in the settings menu\n');
  
  console.log('6️⃣  You\'ll see two important values:\n');
  console.log('   📍 Project URL');
  console.log('      • Located under "Project URL" section');
  console.log('      • Looks like: https://xxxxxxxxxxxxx.supabase.co');
  console.log('      • Click the "Copy" button to copy it\n');
  
  console.log('   🔑 anon public key');
  console.log('      • Located under "Project API keys" section');
  console.log('      • Look for the key labeled "anon" or "public"');
  console.log('      • It\'s a long string starting with "eyJ..."');
  console.log('      • Click the "Copy" button (👁️ eye icon) to reveal and copy it\n');
  
  console.log('💡 TIP: Keep this browser tab open so you can easily copy the values!\n');
  console.log('='.repeat(70) + '\n');
  
  const continueSetup = await question('Ready to enter your Supabase credentials? (Press Enter to continue, or type "exit" to cancel): ');
  
  if (continueSetup.toLowerCase().trim() === 'exit') {
    console.log('\n👋 Setup cancelled. Run "npm run setup:env" again when you\'re ready!\n');
    rl.close();
    process.exit(0);
  }
  
  console.log('\n');
}

async function main() {
  console.log('\n🚀 Supabase Environment Setup\n');
  console.log('This script will help you configure your Supabase environment variables.\n');
  
  const existingEnv = readExistingEnv();
  const needsSetup = !existingEnv.NEXT_PUBLIC_SUPABASE_URL || !existingEnv.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  
  if (needsSetup) {
    await showInstructions();
  } else {
    console.log('✅ Found existing configuration. You can update values if needed.\n');
  }

  const newEnv = { ...existingEnv };
  let hasChanges = false;

  // Check each required variable
  for (const [key, config] of Object.entries(REQUIRED_VARS)) {
    const existingValue = existingEnv[key];
    let value = existingValue;

    if (existingValue) {
      console.log(`\n📋 Found existing value for ${config.description}:`);
      console.log(`   ${key}=${existingValue.substring(0, 50)}${existingValue.length > 50 ? '...' : ''}`);
      
      const overwrite = await question(`\n❓ Do you want to update this value? (y/N): `);
      if (overwrite.toLowerCase() !== 'y' && overwrite.toLowerCase() !== 'yes') {
        console.log('   ✓ Keeping existing value\n');
        continue;
      }
    }

    // Prompt for new value
    let isValid = false;
    let attemptCount = 0;
    while (!isValid) {
      if (attemptCount === 0) {
        console.log(`\n${'─'.repeat(60)}`);
        console.log(`📝 ${config.description}`);
        console.log(`${'─'.repeat(60)}`);
        if (key === 'NEXT_PUBLIC_SUPABASE_URL') {
          console.log('\n   📍 Where to find it:');
          console.log('      • Supabase Dashboard → Settings → API');
          console.log('      • Look for "Project URL" section');
          console.log('      • Copy the URL (starts with https://)');
        } else if (key === 'NEXT_PUBLIC_SUPABASE_ANON_KEY') {
          console.log('\n   🔑 Where to find it:');
          console.log('      • Supabase Dashboard → Settings → API');
          console.log('      • Look for "Project API keys" section');
          console.log('      • Find the "anon" or "public" key');
          console.log('      • Click the 👁️ icon to reveal it, then copy');
        }
        console.log(`\n   💡 ${config.hint}\n`);
      } else {
        console.log(`\n   🔄 Let's try again. ${config.hint}\n`);
      }
      
      value = await question(`   Enter ${key}: `);
      attemptCount++;

      const validationError = config.validate(value);
      if (validationError) {
        console.log(`\n   ❌ Error: ${validationError}`);
        console.log('   Please try again.\n');
        continue;
      }

      value = value.trim();
      isValid = true;
    }

    if (value !== existingValue) {
      newEnv[key] = value;
      hasChanges = true;
      console.log(`   ✓ ${config.description} saved\n`);
    }
  }

  // Write the file
  if (hasChanges || !fs.existsSync(ENV_FILE)) {
    writeEnvFile(newEnv);
    console.log('\n' + '='.repeat(70));
    console.log('✅ SUCCESS! Configuration saved');
    console.log('='.repeat(70));
    console.log('\n📄 File location: ' + ENV_FILE);
    console.log('\n🎉 Setup complete! Next steps:\n');
    console.log('   1. Make sure your development server is running');
    console.log('   2. If it\'s already running, restart it with: npm run dev');
    console.log('   3. Refresh your browser to see your website!\n');
    console.log('💡 The .env.local file is automatically ignored by git,');
    console.log('   so your credentials won\'t be committed to version control.\n');
  } else {
    console.log('\n✓ No changes made. Your .env.local file is already configured.\n');
  }

  rl.close();
}

// Handle errors gracefully
main().catch((error) => {
  console.error('\n❌ Error:', error.message);
  console.error('\nPlease check your input and try again.\n');
  rl.close();
  process.exit(1);
});

